### ISSUE TITLE
我纠正，GPL不是个笑话，但是对于hmclpe的维护者以及某个地区的法律，他是个笑话

### ISSUE THREAD

**Issue by DreamOneX** [577fkj/FuckHMCLPE#3]
不过hmclpe的某些行为，确实让我认为它把GPL当成了笑话  
我本意是：**HMCL-PE的维护者认为GPL是个笑话**  
* https://github.com/AOF-Dev/Boat/issues/26  
* https://github.com/yushijinhun/authlib-injector/issues/168  
* https://github.com/PojavLauncherTeam/PojavLauncher/issues/3415  

<details>
<summary></summary>
如果你看过我的profile你应该知道我也支持GPL，可惜是某地区的法律确实让他沦为笑话，除了HMCL-PE之外，很多项目（包括很大一部分在此地区的商业项目），都有侵犯GPL的行为，但是，基本无力应对  谢谢你的项目，让我更深刻的认识到社区的力量   
最后：  社区万岁！    
</details>

**Comment by 577fkj** [comment]
是的，对于HMCLPE的维护者来说GPL就是个笑话，他们根本就不尊重GPL协议，我只能已这样的方式进行回击。

**Comment by qwq233** [comment]
![image](https://user-images.githubusercontent.com/20317838/177030088-eee2881b-e199-4504-87b5-0c68426ee162.png)

**Comment by 577fkj** [comment]
🤔🤔🤔

**Comment by DreamOneX** [comment]
> ![image](https://user-images.githubusercontent.com/20317838/177030088-eee2881b-e199-4504-87b5-0c68426ee162.png)
> 

我是hmclpe的管理没错，但我和hmclpe的维护者没有任何关系，我也经常在那个群里和他们两个关于内测撕逼

**Comment by DreamOneX** [comment]
> > ![image](https://user-images.githubusercontent.com/20317838/177030088-eee2881b-e199-4504-87b5-0c68426ee162.png)
> > 
> 
> 我是hmclpe的管理没错，但我和hmclpe的维护者没有任何关系，我也经常在那个群里和他们两个关于内测撕逼
> 
> 就这么说吧，那个群只有两个管理，也就是Tungstend和mio与hmclpe项目本身有关 :-)

我纠正，三个，还有个tungstend小号

**Comment by TSaltedfishKing** [comment]
🤔

**Comment by DreamOneX** [comment]
如果你们仍然保持🤔的态度  
这是个撕逼现场
* zhangjing-GitHub-Code/HMCL-PE/pull/7

**Comment by TSaltedfishKing** [comment]
不置可否，大多数都是这样的，坚守本心可以，我行我素可以，但所谓社区已经低质量下来，所谓正义也出现了不少问题
🤔个人不知事情原委，所谓正义是否过头了呢
HMCL-PE维护者，，，也没得说了，协议是犯了，态度也，，，
正义就一定要以相同手段执行么

**Comment by TSaltedfishKing** [comment]
经过充分友好协商本应能解决，为什么要上升到如此层面呢

**Comment by DreamOneX** [comment]
> 经过充分友好协商本应能解决，为什么要上升到如此层面呢

我在此issue中提及了 Tungstend/HMCL-PE#27 但原库已删无从考证
* AOF-Dev/Boat#26

在我印象中 @qwq233 所提交的两个issue也提及了 Tungstend/HMCL-PE#27
* https://github.com/PojavLauncherTeam/PojavLauncher/issues/3415
* https://github.com/yushijinhun/authlib-injector/issues/168

此PR中，要求删除缺失组件，如果我没有搞错 本项目README中我说的那句话应该来自那个PR HMCL-PE维护者拒绝删除相关组件，并解释道：
> 本地编译中有用到，不接

**Comment by TSaltedfishKing** [comment]
同样认为是拒绝协商，同样有如此看法
>但相应责任很显然不是号被盗

@Tungstend @ghost

希望能做出解释，也希望双方能把精力用在刀刃上

_关于我呼叫ghost这件事_

**Comment by qwq233** [comment]
> 不置可否，大多数都是这样的，坚守本心可以，我行我素可以，但所谓维权社区已经低质量下来，所谓正义也出现了不少问题 thinking个人不知事情原委，所谓正义是否过头了呢 HMCL-PE维护者，，，也没得说了，协议是犯了，态度也，，， 正义就一定要以相同手段执行么
> 
> 就所知所谓正义行为（局部） 个人认为超出了正义范畴
> 
> 1. 删除Github账户
> 2. 尝试注销Steam账户
> 3. 注销Mcbbs.net账户

原来是有人删的号吗 我还以为是他自己删的

**Comment by DreamOneX** [comment]
这个issue我现在先关了，讨论已经离题了，我最后阐明我的立场 
* 支持HMCLPE维护者通过赞助获取报酬 
* 尊重HMCLPE维护者劳动成果 
* 不支持HMCLPE维护者拒绝遵守GPL的行为 
* 不站在双方任何一方 
*  不对任何人抱有攻击意图片及不满  

我给双方一点建议（个人建议，如有错误，请多加斧正）：
* 虽然我们国家的法律并不认可DMCA，但是遵守GPL许可证是每个开发者应该履行的义务，法律没有限制，不代表道德没有限制
* 这件事情本应私下解决，上升到这种高度我认为双方都有问题，当然我也有问题，应该更进一步友好协商
* 不希望双方因此产生摩擦与攻击
Thanks.

**Comment by 577fkj** [comment]
> 这个issue我现在先关了，讨论已经离题了，我最后阐明我的立场
> 
> * 支持HMCLPE维护者通过赞助获取报酬
> * 尊重HMCLPE维护者劳动成果
> * 不支持HMCLPE维护者拒绝遵守GPL的行为
> * 不站在双方任何一方
> * 不对任何人抱有攻击意图片及不满
> 
> 我给双方一点建议（个人建议，如有错误，请多加斧正）：
> 
> * 虽然我们国家的法律并不认可DMCA，但是遵守GPL许可证是每个开发者应该履行的义务，法律没有限制，不代表道德没有限制
> * 这件事情本应私下解决，上升到这种高度我认为双方都有问题，当然我也有问题，应该更进一步友好协商
> * 不希望双方因此产生摩擦与攻击
>   Thanks.

其实中国法院是支持GPL协议的(已经有案例了)
我只参与了模块开发与so分析，至于销号则是其他人的所作所为，与我无关
很感谢你能来讨论

**Comment by qwq233** [comment]
> 这个issue我现在先关了，讨论已经离题了，我最后阐明我的立场
> 
> * 支持HMCLPE维护者通过赞助获取报酬
> * 尊重HMCLPE维护者劳动成果
> * 不支持HMCLPE维护者拒绝遵守GPL的行为
> * 不站在双方任何一方
> * 不对任何人抱有攻击意图片及不满
> 
> 我给双方一点建议（个人建议，如有错误，请多加斧正）：
> 
> * 虽然我们国家的法律并不认可DMCA，但是遵守GPL许可证是每个开发者应该履行的义务，法律没有限制，不代表道德没有限制
> * 这件事情本应私下解决，上升到这种高度我认为双方都有问题，当然我也有问题，应该更进一步友好协商
> * 不希望双方因此产生摩擦与攻击
>   Thanks.

我们国家有著作权法，国内也有gpl的法例

**Comment by DreamOneX** [comment]
@qwq233 @577fkj 谢谢普及，无论如何，这件事情貌似产生的影响已经过大了，原仓库已被删除，现在是完全遵守GPL许可证的版本（虽然分发的二进制文件并不是）；据我所知，按我国法律，只有项目所有者才能对违规者提起诉讼，而无论是pojav团队还是AOF团队，应该都没有钱力和精力维护他们的项目权益  
**不希望这件事继续闹大，而且，由于上面的原因，继续闹大这件事情，也会不了了之**，个人观点，如有意见，欢迎提出

**Comment by qwq233** [comment]
> @qwq233 @577fkj 谢谢普及，无论如何，这件事情貌似产生的影响已经过大了，原仓库已被删除，现在是完全遵守GPL许可证的版本（虽然分发的二进制文件并不是）；据我所知，按我国法律，只有项目所有者才能对违规者提起诉讼，而无论是pojav团队还是AOF团队，应该都没有钱力和精力维护他们的项目权益 **不希望这件事继续闹大，而且，由于上面的原因，继续闹大这件事情，也会不了了之**，个人观点，如有意见，欢迎提出
> 
> 补充
> 
> 1. 我阐述现在的GitHub仓库是为了说明 Github Staff 无法帮助 AOF团队和Pojav团队
> 2. 即使 GitHub 仓库 不再更新 不发布release，他们还有其他平台分发二进制文件

著作权拥有者可以授权全权代理或一般授权代理进行维权
